.TH YGET 1
.SH NAME
yget \- download youtube videos
.br
yplay \- play youtube videos
.br
yurl \- print youtube download URLs and additional informations

.SH SYNOPSIS
.B yget
.RB URL \ [ \-hq | \-fmt\ fmtlist | \-prefix\ prefix ]
.br
.B yplay
.RB URL \ [ \-hq | \-fmt\ fmtlist ]
.br
.B yurl
.RB URL

.SH DESCRIPTION
.B yget
saves the video of the given youtube URL. The filename is created from the
given prefix, an ascii name and the video id. The default prefix is "y_".
If the URL points to a playlist then
.B yget
will download all videos in it and save them with prefix "y[number]_".
If the filename already exists then
.B yget
assumes that the video is unfinished and tries to continue the download.
.P
Higher quality video format can be selected by -hq and -fmt allows to
select the format directly.
.P
.B yplay
streams the video of the given youtube URL.
.P
.B yurl
prints a key value pair list about the given youtube URL
(download url, title, length, etc.).

.SH EXAMPLES
yplay "youtube.co.uk/watch?v=abcdefghijk&foo=123&bar=456"
.br
yget youtu.be/abcdefghijk
.br
yget abcdefghijk
.br
yget http://www.youtube.com/view_play_list?p=abcdefghijklmnop
.br
yurl http://youtube.com/p/abcdefghijklmnop

.SH NOTES
If the URL has query parameters ("&foo=bar") then the "&" might need to
be escaped in the shell. Internally these parameters are dropped, only
the video or playlist id is used.
.P
.B yget
and
.B yplay
try to get a 640x360 resolution H.264 encoded version (fmt=34).
For other versions see the download url## from
.B yurl
or use -fmt.
(possible fmt parameters are 5 6 13 17 18 22 34 35 36 37 43 45 82 84 100 102)
.P
Any recent mplayer or vlc should be able to stream the video from the
urls printed by
.BR yurl .
Seeking in the stream might not work.
.B yplay
uses mplayer.
