#!/bin/sh
# TODO: fmt = 0 5 6 13 17 18 22 34 35 37
[ "$1" ] || { echo "usage: $0 URL [prefix=y]"; exit 1; }
[ "$2" ] || set "$1" y
./yurl "$1" |awk -v prefix="$2" -v cmd="$0" '
/^000/ {list = 1}
!list && /^url/ {url=$2}
!list && /^id/ {id=$2}
{print}
list { sub(/&.*/, ""); system(cmd " " $2 " " prefix $1 "_" ) }
END {
	if (url)
		system("wget -c -O " prefix id ".mp4 '\''" url "&fmt=18'\''")
}'
