#!/bin/sh

fmts="34 18 5 6 13 17 22 35 36 37 43 45 82 84 100 102"
hqfmts="22 35 37 34"
url=

usage() {
	echo "usage: $0 [-hq|-fmt fmtlist] URL" 1>&2
	echo "  -hq     - high quality, equivalent to -fmt '$hqfmts'" 1>&2
	echo "  -fmt    - format preference, default: '$fmts'" 1>&2
	exit 1
}

while [ $# -gt 0 ]; do
	case "$1" in
	-hq ) fmts="$hqfmts"; shift 1;;
	-fmt ) fmts="$2"; shift 2;;
	* ) url="$1"; shift 1;;
	esac
done
[ "x$url" != "x" ] || usage

yurl "$url" |awk -v fmts="$fmts" '
function fix() {
	gsub("'\''","")
}
/^00/ {
	print "playlist is not supported" >"/dev/stderr"
	exit 1
}
{
	print
}
/^url/ {
	fix()
	sub(/url/, "")
	url[$1] = $2
}
/^title/ {
	fix()
	sub(/^title[ \t]*/,"")
	t="MPlayer - " $0
}
END {
	n = split(fmts, a)
	for (i = 1; i <= n; i++)
		if (url[a[i]]) {
			u = url[a[i]]
			break
		}
	if (u)
		system("mplayer -cache 32768 -cache-min 1 -cache-seek-min 10 -title '\''" t "'\'' '\''" u "'\''")
}'
