#!/bin/sh
[ $1 ] || echo "usage: $0 url"
[ $1 ] || exit 1
URL=`echo "$1"|sed 's|/v/|/watch?v=|;s|\?.*&v=|?v=|;s|&.*||'`
URL=`wget $URL -O- |grep -m1 'var swfArgs'|sed 's|.*"t": "\([^"]*\)".*|http://youtube.com/get_video?t=\1\&video_id=|'``echo $URL|tail -c12`
mplayer -prefer-ipv4 -cache 4096 $URL'&fmt=18' || mplayer -prefer-ipv4 -cache 4096 $URL
